# Stage 1: Build
FROM node:24-alpine3.21 AS build

LABEL org.opencontainers.image.authors="Jupyter Project <jupyter@googlegroups.com>"
LABEL org.opencontainers.image.source="https://github.com/jupyterhub/configurable-http-proxy"
LABEL org.opencontainers.image.url="https://github.com/jupyterhub/configurable-http-proxy/blob/HEAD/Dockerfile"

RUN apk upgrade --no-cache \
 && apk add --no-cache \
        curl \
        jq

WORKDIR /srv/configurable-http-proxy
COPY . /srv/configurable-http-proxy

RUN npm ci --production \
 && npm uninstall -g npm

# Stage 2: Final
ARG BASE_REGISTRY=201959883603.dkr.ecr.us-east-2.amazonaws.com
ARG BASE_IMAGE_PATH=mdaca/base-images/ironbank-alpine
ARG BASE_TAG=3.20.7
ARG BASE_IMAGE=${BASE_REGISTRY}/${BASE_IMAGE_PATH}:${BASE_TAG}

FROM ${BASE_IMAGE} AS final


RUN apk upgrade --no-cache \
 && apk add --no-cache \
        bash
# Copy from build stage with static timestamp
COPY --from=build --timestamp="2025-08-27T12:33:00Z" /srv/configurable-http-proxy /srv/configurable-http-proxy
WORKDIR /srv/configurable-http-proxy
EXPOSE 8000
EXPOSE 8001
USER 65534
ENV PATH=/srv/configurable-http-proxy/bin:$PATH
ENTRYPOINT ["/srv/configurable-http-proxy/chp-docker-entrypoint"]
